### ISSUE TITLE
SearchableDataObject onBeforeDelete override calls parent::onAfterDelete()

### ISSUE THREAD

**Issue by maxime-rainville** [g4b0/silverstripe-searchable-dataobjects#13]
I was looking at the code for the `onBeforeDelete` function on the `SearchableDataObject` class.

I'm not sure if this is done on purpose or not, but on line 45, it calls `parent::onAfterDelete()`.

It seems to me like `parent::onBeforeDelete()` should be called in this instance, not `parent::onAfterDelete()`.

Thanks a lot for this plugins. It's really helpful and saved me a lot of time.

**Comment by g4b0** [comment]
Solved in 1.0.4, thaks a lot
