### ISSUE TITLE
Provide own search controller

### ISSUE THREAD

**Issue by wernerkrauss** [g4b0/silverstripe-searchable-dataobjects#15]
searching on the current page might be simple but not the most elegant solution.

Also it conflicts with custom `$url_handlers` like we use when trying to eleminating actions (aka [url slug](https://github.com/NightJar/silverstripe-slug/)).

**Comment by g4b0** [comment]
Could you please explain more in depth the issue?

**Comment by wernerkrauss** [comment]
Well, when doing a search the url currently is `/path/to/page/SearchForm?Search=foo` which is no unique path to search results (cause it contains the current page's url) and might conflict with a default url handler that is defined in the page controller.

IMHO it'd be better and cleaner if the searchform would point to a dedicated controller with a configurable route or search page, e.g. `/search/?search=foo`. I already tried something like that, if you're interested i can make a work-in-progress PR ;)
