### ISSUE TITLE
mysql error on a fresh install

### ISSUE THREAD

**Issue by wernerkrauss** [g4b0/silverstripe-searchable-dataobjects#16]
tryting to deploy my website i get the following error on the very first dev/build on a clean database:

[User Error] Couldn't run query: INSERT INTO `SearchableDataObjects` (`ID`, `ClassName`, `Title`, `Content`) VALUES (2, 'Page', 'Ãœber uns', 'Sie kÃ¶nnen diese Seite mit Ihren eigenen Inhalten fÃ¼llen, oder sie lÃ¶schen und Ihre eigenen Seiten erstellen.') ON DUPLICATE KEY UPDATE Title='Ãœber uns', Content='Sie kÃ¶nnen diese Seite mit Ihren eigenen Inhalten fÃ¼llen, oder sie lÃ¶schen und Ihre eigenen Seiten erstellen.' Table 'silverstripe.SearchableDataObjects' doesn't exist

Guess it's cause onAfterPublish hook tries to update the non existent table. Any way to check if the table exists before trying to update?

**Comment by wernerkrauss** [comment]
Seems that table is generated when running dev/tasks/PopulateSearch the first time? Any chance to get it running on the first dev/build before populating the dataobjects ?

**Comment by wernerkrauss** [comment]
could be created by creating a `requireDefaultRecords()` method in the DataExtension which should be applied to SiteTree or a DataObject

**Comment by g4b0** [comment]
Fixed in 2.0 
Be aware that 2.0 works only with SS >= 3.1.13
