### ISSUE TITLE
PaginatedList properties are protected..

### ISSUE THREAD

**Issue by axyr** [g4b0/silverstripe-searchable-dataobjects#2]
.. so they can't be set directly in CustomSearch::getSearchResults();

You need to use : 
$ret = new PaginatedList($list);
$ret->setPageLength(10);
$ret->setPageStart($s);
$ret->setTotalItems($list->count());
$ret->setLimitItems(10);

**Comment by g4b0** [comment]
Thanks a lot, solved in master.
