### ISSUE TITLE
readme.md example DataObject class code bug

### ISSUE THREAD

**Issue by HARVS1789UK** [g4b0/silverstripe-searchable-dataobjects#21]
Hi Gabriele,

Just getting to grips with your module which looks good so far, one thing that has had me stuck trying to get it working for some time was that the readme.md example code of how to set up a DataObject to be searchable contains the following:

```
    /**
     * FilterByCallback function (optional)
     * eg. function($object){
     *  return ($object->StartDate > date('Y-m-d') || $object->isStillRecurring());
     * };
     * @return array
     */
    public static function getSearchFilterByCallback() {
        return function($object){};
    }
```

having investigated, I can see that the PopulateSearch class (which seems to be run via /dev/tasks/PopulateSearch and onAfterWrite of any DataObject which is being made searchable) contains the following conditional statement for each DataObject marked as being searchable:

```
if(method_exists($class, 'getSearchFilterByCallback')){
                $dos = $dos->filterByCallback($class::getSearchFilterByCallback());
}
```

Although I do appreciate your comments above the getSearchFilterByCallback() method do provide an example of a callback method, I had assumed that the default function in your example ( ```function($object){};``` ) would have ben sufficient, but the lack of any return statement means that this example effectively returns false every time it is run.

This means that none of my DataObjects were being stored in the SearchableDataObjects database table (as getSearchFilterByCallback() was excluding them all) and therefore none were showing up in the search.

I would suggest making the example method contain ```return true;``` would be a logical addition and hopefully save others some time and not following the same path as I did. For example:

```
    /**
     * FilterByCallback function (optional)
     * eg. function($object){
     *  return ($object->StartDate > date('Y-m-d') || $object->isStillRecurring());
     * };
     * @return array
     */
    public static function getSearchFilterByCallback() {
        return function($object){return true;};
    }
```

**Comment by g4b0** [comment]
@muskie9 what do you think about that? It seems reasonable, isn't it?

**Comment by muskie9** [comment]
I think that's fine for the example code. I would suggest though that if you aren't going to be running anything in the closure other than `return true;` to not include `getSearchFilterByCallback()` on the object as it may have unintended results since it's a hard `true`.

**Comment by HARVS1789UK** [comment]
Hi @muskie9 

Agreed, now that I have read through the code and seeing a check is made to see if the method exists I could just as easily remove the ```getSearchFilterByCallback()``` method from my DataObject (which I will probably do).

Just thought I would raise the potential time saver in the example code in README.md as I expect that many users of the module will (like me) be lazy and copy the example code to get the module up and running ASAP and many of them may also spend some time wondering why their DO's are still not showing up in search. Up to you guys if you want to make the change or not, just thought id suggest it.

Kind regards,

HARVS1789UK

**Comment by muskie9** [comment]
I think it's a good suggestion, probably a good idea to describe `filterByCallback()` usage a bit as well. I started looking around the SilverStripe docs but there's nothing in there that I could find for that filter type. Only a single example in the API.
