### ISSUE TITLE
HTMLPurifier requires a Cache Folder

### ISSUE THREAD

**Issue by axyr** [g4b0/silverstripe-searchable-dataobjects#3]
This will not be created on install, but is required.
See also : 
https://github.com/symphonycms/symphony-2/issues/2094

I did a quick fix by creating a folder DefinitionCache/Serializer in HTMLPurifier,
but I guess this might be set with dependency injection in the searchable module?

**Comment by g4b0** [comment]
I think this issue is related to my module https://github.com/g4b0/silverstripe-htmlpurifier
Can you please open an issue there providing an example? I never had caching problem with this module, maybe is a permission problem in yous setup?
