### ISSUE TITLE
Return 1 Page when Multiple DataObject ComeBack

### ISSUE THREAD

**Issue by thezenmonkey** [g4b0/silverstripe-searchable-dataobjects#31]
I'm using the modules to search content blocks on my site, but it returns a seperate entry for each dataobject, I'd like to only return the page once if the word is found. Is this possible?

**Comment by g4b0** [comment]
Try using this module, that'sa fork of this one: https://github.com/firebrandhq/silverstripe-searchable-dataobjects

**Comment by g4b0** [comment]
@thezenmonkey does the module above solved your problem?

**Comment by thezenmonkey** [comment]
Yes, that one worked much better thanks.

**Comment by g4b0** [comment]
It's not better, it does different things :)
