### ISSUE TITLE
SS 3.3.1: tons of "Title" indexes

### ISSUE THREAD

**Issue by wernerkrauss** [g4b0/silverstripe-searchable-dataobjects#36]
see #23 

On SS 3.3.1 i see tons of "Title" indexes after running dev/build. It creates 20 new indexes when running dev/build once.

I'm on dev-master 7c0220f

**Comment by wernerkrauss** [comment]
I wonder why it was fixed in 2.1.3 but is not in dev-master...?
https://github.com/g4b0/silverstripe-searchable-dataobjects/commit/b8b0bfe047252956d9556e587c2477a744b652a8

Which brings me again to #26 - why not just use a DO for saving the search - this way you can use extensions for additional search information and SS will handle the index creation.

**Comment by g4b0** [comment]
Yes, maybe #26 should be the right way to handle it. A PR would be really appreciated :D

**Comment by rotassator** [comment]
My take on fixing this that also works in SQLite - https://github.com/g4b0/silverstripe-searchable-dataobjects/pull/38

> why not just use a DO for saving the search
I thought about this, but AFAIK the ORM would use the ID for the lookup and break since the primary index is on ID + ClassName.

**Comment by g4b0** [comment]
@wernerkrauss are you ok with the new PR?

**Comment by wernerkrauss** [comment]
I hope I can have a look at at this weekend. Looks good but would need some testing... 

Just wondering if i can write a unit test for that?

**Comment by g4b0** [comment]
Sure you can! This module is growing and some unit test shoud be very useful. We can then also try to integrate some CI like travis, but first we need some test :)
Thanks a lot, I will be very happy to merge your PR

**Comment by g4b0** [comment]
@wernerkrauss does this PR solve your issue? Can we close the issue?

**Comment by wernerkrauss** [comment]
@g4b0 Seems it fixed the problem. I ran a quick test, deleted the actual SearchableDataObjects table and it created only two indexes, Title and Content.  Tested with dev-master d2e02b7

Thanks!

**Comment by g4b0** [comment]
thanks to  you and @rotassator
