### ISSUE TITLE
Module does not work on sqlite - tests with sqlite not working

### ISSUE THREAD

**Issue by wernerkrauss** [g4b0/silverstripe-searchable-dataobjects#37]
related to #26 / ORM replacement

As the module generates the table manually it's logic is bound to mysql only. Unfortunately this also blocks me from running tests on other modules using faster sqlite.

**Comment by rotassator** [comment]
I've submitted a PR to address this: https://github.com/g4b0/silverstripe-searchable-dataobjects/pull/38

**Comment by g4b0** [comment]
@wernerkrauss are you ok with the new PR?
