### ISSUE TITLE
getSearchFilter null results in addFilter warning

### ISSUE THREAD

**Issue by axyr** [g4b0/silverstripe-searchable-dataobjects#4]
When setting : 
public static function getSearchFilter() {
        return null;
}

This will result in a warning : 
[Warning] Invalid argument supplied for foreach() in DataList->addFilter() ;

using an empty array will fix this : 

public static function getSearchFilter() {
        return array();
    }

**Comment by axyr** [comment]
This happens when running dev/tasks/PopulateSearch

**Comment by g4b0** [comment]
Updated Readme, thanks!
