### ISSUE TITLE
SearchForm results() function exposed as controller action

### ISSUE THREAD

**Issue by rotassator** [g4b0/silverstripe-searchable-dataobjects#42]
Browsing to a page ending in ~/results causes the following error:

```
[Error] in searchable-dataobjects/code/CustomSearch.php:110 (http://testdomain.com/page/results)
```

The `results()` function is being exposed to the controller as an `$allowed_action`, but should only be available to the form processor.

Using SilverStripe 3.6.5.

Issue also exists in SilverStripe CMS: https://github.com/silverstripe/silverstripe-cms/issues/2125

**Comment by rotassator** [comment]
Thanks for merging. Could we also please have a new release, say 4.1.1? Thanks!

**Comment by g4b0** [comment]
Here you are :)
