### ISSUE TITLE
SearchableDataObject does take into account SiteTree versioned

### ISSUE THREAD

**Issue by axyr** [g4b0/silverstripe-searchable-dataobjects#5]
SearchableDataObject::onAfterWrite gives ambigous ID when saving a Page with extra fields.
This fixes the problem for me:

$table = $this->owner->class;
            if(is_a($this->owner, 'SiteTree') && Versioned::current_stage() == 'Live') {
                $table = 'SiteTree_Live';
            }
            $filterID = $table . ".ID={$this->owner->ID}";

**Comment by g4b0** [comment]
Please provide a PR, I will be happy to merge it.

**Comment by g4b0** [comment]
Now that versions are handled in SearchableDataObject::onAfterWrite do you think that I can close your issue, or it's still valid?

**Comment by g4b0** [comment]
Thanks @rotassator , I've also created a new 4.x tag, since it breaks compatibility with 3.1.x
